import { CheckCircle2, CircleAlert, ExternalLink, Save } from "lucide-react"
import { updatePortfolioProjects } from "@/lib/actions/profile"
import { getPortfolioProfile } from "@/lib/profile"

type PageProps = { searchParams: { saved?: string; error?: string } }
const inputClass = "mt-2 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
const labelClass = "block text-sm font-medium text-slate-200"

export default async function ProjectsAdminPage({ searchParams }: PageProps) {
  const profile = await getPortfolioProfile()
  return <div className="space-y-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-emerald-400">Site content</p><h1 className="mt-2 text-3xl font-bold">Projects section</h1><p className="mt-2 max-w-2xl text-slate-400">Manage featured projects. Images currently use paths to files stored in the public directory, for example /project-image.jpg.</p></div><a href="/#projects" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-cyan-400">View section <ExternalLink className="h-4 w-4" /></a></div>
    {searchParams.saved && <div className="flex items-center gap-3 rounded-md border border-emerald-800 bg-emerald-950/40 px-4 py-3 text-sm text-emerald-300"><CheckCircle2 className="h-5 w-5" /> Projects saved successfully.</div>}{searchParams.error && <div className="flex items-center gap-3 rounded-md border border-rose-900 bg-rose-950/40 px-4 py-3 text-sm text-rose-300"><CircleAlert className="h-5 w-5" /> Check required fields, image paths, and complete URLs.</div>}
    <form action={updatePortfolioProjects} className="space-y-6"><input type="hidden" name="projectCount" value={profile.projects.length} /><fieldset className="grid gap-5 rounded-lg border border-slate-800 bg-slate-900 p-5"><legend className="px-2 text-lg font-semibold">Section content</legend><label className={labelClass}>Heading<input className={inputClass} name="projectsHeading" defaultValue={profile.projectsHeading} required /></label><label className={labelClass}>Description<textarea className={inputClass} name="projectsSectionDescription" defaultValue={profile.projectsDescription} rows={2} required /></label></fieldset>
      {profile.projects.map((project, index) => <fieldset key={`${project.title}-${index}`} className="grid gap-5 rounded-lg border border-slate-800 bg-slate-900 p-5 md:grid-cols-2"><legend className="px-2 text-lg font-semibold">Project {index + 1}</legend><label className={labelClass}>Title<input className={inputClass} name={`projectTitle${index}`} defaultValue={project.title} required /></label><label className={labelClass}>Subtitle<input className={inputClass} name={`projectSubtitle${index}`} defaultValue={project.subtitle} required /></label><label className={labelClass}>Category<input className={inputClass} name={`projectCategory${index}`} defaultValue={project.category} required /></label><label className={labelClass}>Status<input className={inputClass} name={`projectStatus${index}`} defaultValue={project.status} required /></label><label className={`${labelClass} md:col-span-2`}>Description<textarea className={inputClass} name={`projectDescription${index}`} defaultValue={project.description} rows={3} required /></label><label className={labelClass}>Public image path<input className={inputClass} name={`projectImage${index}`} defaultValue={project.image} placeholder="/project-image.jpg" required /></label><label className={labelClass}>Company<input className={inputClass} name={`projectCompany${index}`} defaultValue={project.company} /></label><label className={labelClass}>Live URL<input className={inputClass} name={`projectLiveUrl${index}`} type="url" defaultValue={project.liveUrl} /></label><label className={labelClass}>GitHub URL<input className={inputClass} name={`projectGithubUrl${index}`} type="url" defaultValue={project.githubUrl} /></label><label className={labelClass}>Technologies <span className="font-normal text-slate-500">(comma separated)</span><textarea className={inputClass} name={`projectTechnologies${index}`} defaultValue={project.technologies.join(", ")} rows={5} required /></label><label className={labelClass}>Features <span className="font-normal text-slate-500">(one per line)</span><textarea className={inputClass} name={`projectFeatures${index}`} defaultValue={project.features.join("\n")} rows={5} required /></label></fieldset>)}
      <div className="sticky bottom-4 flex justify-end rounded-lg border border-slate-800 bg-slate-900/95 p-4 shadow-xl backdrop-blur"><button type="submit" className="inline-flex items-center gap-2 rounded-md bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-emerald-400"><Save className="h-4 w-4" />Save projects</button></div></form>
  </div>
}